### ISSUE TITLE
unhadled promise and Cannot destructure property 'rules' of '(intermediate value)' as it is undefined.

### ISSUE THREAD

**Issue by jsprogr** [BorisChumichev/vkflow#2]
Решил познакомиться с vkflow, но вот выловил unhandled promise пульнул себе локально, исправил, добавил там где надо catch. Но потом пошли проблемы с rules:
UnhandledPromiseRejectionWarning: 
TypeError: Cannot destructure property 'rules' of '(intermediate value)' as it is undefined.
    at flushRules (C:\Users\obois\YandexDisk\work\0.00 Starters\websockets\vkwebsocket\lib\http-client.js:67:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async setupStream (C:\Users\obois\YandexDisk\work\0.00 Starters\websockets\vkwebsocket\lib\factory.js:8:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BorisChumichev** [comment]
> Решил познакомиться с vkflow, но вот выловил unhandled promise

— пожалуйста, приложите пример кода, который привел к ошибке.

**Comment by jsprogr** [comment]
Забавно, я подставил сервисный ключ от другого вк приложения и заработало, прошу прощение за беспокойство.
